apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "persister.fullname" . }}
data:
    application.properties: |
        ##connect to database
        server.port=9001
        spring.datasource.driver-class-name=org.postgresql.Driver
        spring.datasource.url = jdbc:postgresql://{{ .Values.pg.host }}.{{ .Release.Namespace }}.svc:{{ .Values.pg.port }}/quokka
        spring.datasource.username = {{ .Values.pg.user }}
        spring.datasource.password = {{ .Values.pg.password }}

        ##JPA Config
        #
        #spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
        #spring.jpa.hibernate.ddl-auto = update
        #spring.jpa.show-sql = true
        #spring.jpa.properties.hibernate.format_sql = true

        #spring.jpa.database-platform = org.hibernate.dialect.PostgreSQL94Dialect
        spring.jpa.database-platform = org.hibernate.dialect.PostgreSQL94Dialect
        #spring.jpa.show-sql = true
        spring.jpa.hibernate.ddl-auto = validate
        spring.jpa.hibernate.naming.implicit-strategy = org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        spring.jpa.properties.hibernate.format_sql = true

        spring.rabbitmq.addresses = {{ .Values.services.rabbit.host }}.{{ .Release.Namespace }}.svc:{{ .Values.services.rabbit.port }}