{
 "title": "Assetcache",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "asset_type",
    "query": {
     "query": "label_values(quokka_assetcache_stream_trade_total,asset_type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Price Tracker Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Price Tracker match steps stacked duration ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(step) (rate(quokka_assetcache_manager_match_price_tracker_sum{asset_type=~\"$asset_type\"}[$__rate_interval])) / sum by(step) (rate(quokka_assetcache_manager_match_price_tracker_count{asset_type=~\"$asset_type\"}[$__rate_interval]))",
     "legendFormat": "{{step}}"
    }
   ]
  },
  {
   "title": "Price Tracker store duration",
   "type": "heatmap",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(le) (rate(quokka_assetcache_manager_store_price_tracker_bucket{asset_type=~\"$asset_type\"}[$__rate_interval]))",
     "legendFormat": "{{asset_type}}"
    }
   ]
  },
  {
   "title": "Incoming Price Tracker rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "max by(asset_type) (rate(quokka_assetcache_manager_price_tracker_total{asset_type=~\"$asset_type\"}[$__rate_interval]))",
     "legendFormat": "{{asset_type}}"
    }
   ]
  },
  {
   "title": "Price Tracer average store duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(quokka_assetcache_manager_store_price_tracker_sum{asset_type=~\"$asset_type\"}[$__rate_interval]) / rate(quokka_assetcache_manager_store_price_tracker_count{asset_type=~\"$asset_type\"}[$__rate_interval])",
     "legendFormat": "{{asset_type}}"
    }
   ]
  },
  {
   "title": "Number of stored price trackers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "quokka_assetcache_manager_stored_price_tracker{asset_type=~\"$asset_type\"}",
     "legendFormat": "{{asset_type}}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Incoming trades over websocket rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "max by(asset_type) (rate(quokka_assetcache_stream_trade_total{asset_type=~\"$asset_type\"}[$__rate_interval]))",
     "legendFormat": "{{asset_type}}"
    }
   ]
  },
  {
   "title": "Cache price update duration",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by(le) (rate(quokka_assetcache_cache_update_price_bucket{asset_type=~\"$asset_type\"}[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Cache read duration",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "sum by(le) (rate(quokka_assetcache_cache_read_price_bucket{asset_type=~\"$asset_type\"}[$__rate_interval]))",
     "legendFormat": "{{asset_type}}"
    }
   ]
  }
 ]
}